language: groovy
jdk:
  - openjdk7
sudo: false
branches:
  only:
  - master
  - dev
cache:
  directories:
  - "$HOME/.m2"
env:
  - TEST_SCOPE="functional:"
  - TEST_SCOPE='"integration:" org.textup.rest.marshaller.*'
  - TEST_SCOPE='"integration:" org.textup.* org.textup.util.*'
  - TEST_SCOPE='"unit:" org.textup.job.* org.textup.validator.* org.textup.validator.action.* org.textup.type.* org.textup.util.*'
  - TEST_SCOPE='"unit:" org.textup.A* org.textup.B* org.textup.C* org.textup.D* org.textup.E* org.textup.F* org.textup.G* org.textup.H* org.textup.I* org.textup.J* org.textup.K* org.textup.L* org.textup.M*'
  - TEST_SCOPE='"unit:" org.textup.N* org.textup.O* org.textup.P* org.textup.Q* org.textup.R* org.textup.S* org.textup.T* org.textup.U* org.textup.V* org.textup.W* org.textup.X* org.textup.Y* org.textup.Z*'
  - TEST_SCOPE='"unit:" org.textup.media.*'
  - TEST_SCOPE='"unit:" org.textup.rest.* org.textup.test.*'
before_script:
- chmod +x grailsw
- "./grailsw clean"
- "./grailsw refresh-dependencies"
script:
- "./grailsw test-app $TEST_SCOPE"
jobs:
  include:
  - stage: deploy
    env: TEST_SCOPE="none"
    before_install:
    - openssl aes-256-cbc -K $encrypted_8c97747a3917_key -iv $encrypted_8c97747a3917_iv -in .travis/textup.pem.enc -out .travis/textup.pem -d
    script: skip
    after_success:
    - "./grailsw rest-api-doc"
    - "./grailsw prod war"
    before_deploy:
    - chmod +x .travis/deploy-staging.sh
    - chmod +x .travis/deploy-production.sh
    - chmod +x .travis/scripts/set-up-ffmpeg.sh
    - chmod +x .travis/scripts/set-up-temp-directory.sh
    - chmod +x .travis/scripts/build-env-variables.sh
    - chmod +x .travis/scripts/deploy-war.sh
    - chmod 400 .travis/textup.pem
    deploy:
    - provider: script
      script: .travis/deploy-staging.sh
      skip_cleanup: true
      on:
        branch: dev
    - provider: script
      script:  .travis/deploy-production.sh
      skip_cleanup: true
      on:
        branch: master
