language: groovy
jdk:
  - openjdk7

sudo: false

branches:
  only:
  - master
  - dev

cache:
  directories:
    - $HOME/.m2

env:
  - TEST_SCOPE="functional:"
  - TEST_SCOPE='"integration:" org.textup.rest.marshaller.*'
  - TEST_SCOPE='"integration:" org.textup.* org.textup.util.*'
  - TEST_SCOPE='"unit:" org.textup.job.* org.textup.validator.* org.textup.validator.action.* org.textup.type.* org.textup.util.*'
  - TEST_SCOPE='"unit:" org.textup.A* org.textup.B* org.textup.C* org.textup.D* org.textup.E* org.textup.F* org.textup.G* org.textup.H* org.textup.I* org.textup.J* org.textup.K* org.textup.L* org.textup.M*'
  - TEST_SCOPE='"unit:" org.textup.N* org.textup.O* org.textup.P* org.textup.Q* org.textup.R* org.textup.S* org.textup.T* org.textup.U* org.textup.V* org.textup.W* org.textup.X* org.textup.Y* org.textup.Z*'
  - TEST_SCOPE='"unit:" org.textup.rest.*'

before_script:
  - chmod +x grailsw
  - ./grailsw clean
  - ./grailsw refresh-dependencies

script:
  - ./grailsw test-app $TEST_SCOPE

jobs:
  include:
    - stage: deploy
      env: TEST_SCOPE="none"
      before_install:
        - openssl aes-256-cbc -K $encrypted_8c97747a3917_key -iv $encrypted_8c97747a3917_iv -in .travis/textup.pem.enc -out .travis/textup.pem -d
      # inherits global before_script, which refreshes dependencies to enable rest-api-doc
      script: skip # already have run tests, so skip this step
      after_success:
        - ./grailsw rest-api-doc # build latest version of API docs
        - ./grailsw prod war
      before_deploy:
        - chmod +x .travis/deploy.sh
        - chmod 400 .travis/textup.pem
      deploy:
        - provider: script
          script: .travis/deploy.sh $DEPLOY_USER_STAGING $DEPLOY_HOSTNAME_STAGING .travis/textup.pem target textup-backend.war .travis/remote.sh
          skip_cleanup: true
          on:
            branch: dev
        - provider: script
          script: .travis/deploy.sh $DEPLOY_USER_PRODUCTION $DEPLOY_HOSTNAME_PRODUCTION .travis/textup.pem target textup-backend.war .travis/remote.sh
          skip_cleanup: true
          on:
            branch: master
