language: groovy
jdk:
  - openjdk7

sudo: false

branches:
  only:
  - master
  - dev

before_install:
  - openssl aes-256-cbc -K $encrypted_8c97747a3917_key -iv $encrypted_8c97747a3917_iv -in .travis/textup.pem.enc -out .travis/textup.pem -d

before_script:
  - chmod +x grailsw
  - ./grailsw clean
  - ./grailsw refresh-dependencies

script:
  - "./grailsw test-app functional:"
  - "./grailsw test-app integration:"
  - "./grailsw test-app unit: org.textup.job.* org.textup.validator.* org.textup.validator.action.* org.textup.*"
  - "./grailsw test-app unit: org.textup.rest.*"

after_success:
  - ./grailsw prod war

before_deploy:
  - chmod +x .travis/deploy.sh

deploy:
  - provider: script
    script: .travis/deploy.sh $USER_STAGING $HOSTNAME_STAGING .travis/textup.pem target textup-backend.war .travis/remote.sh
    skip_cleanup: true
    on:
      branch: dev
  - provider: script
    script: .travis/deploy.sh $USER_PRODUCTION $HOSTNAME_PRODUCTION .travis/textup.pem target textup-backend.war .travis/remote.sh
    skip_cleanup: true
    on:
      branch: master
