package org.textup

enum CallResponse {
    SELF_GREETING,
    SELF_CONNECTING,
    SELF_INVALID_DIGITS,
    CONNECT_INCOMING,
    VOICEMAIL,
    CONFIRM_BRIDGE,
    FINISH_BRIDGE,
    ANNOUNCEMENT_GREETING,
    HEAR_ANNOUNCEMENTS,
    ANNOUNCEMENT_AND_DIGITS, // so we can loop single announcement
    UNSUBSCRIBED,
    SUBSCRIBED
}
