export TEXTUP_BACKEND_CDN_PRIVATE_KEY_PATH="/cloudfront-sep-2018-private.der"
export TEXTUP_BACKEND_CDN_ROOT="media.textup.org"
export TEXTUP_BACKEND_ENABLE_QUARTZ="true"
export TEXTUP_BACKEND_EXEC_USERNAME="$USER"
export TEXTUP_BACKEND_SERVER_URL="https://v2.textup.org"
export TEXTUP_BACKEND_STORAGE_BUCKET_NAME="media-textup-org"
export TEXTUP_BACKEND_TWILIO_NOTIFICATIONS_NUMBER="+14012878632"
export TEXTUP_BACKEND_URL_ADMIN_DASHBOARD="https://app.textup.org/#/admin"
export TEXTUP_BACKEND_URL_NOTIFY_MESSAGE="https://app.textup.org/#/notify?token="
export TEXTUP_BACKEND_URL_PASSWORD_RESET="https://app.textup.org/#/reset?token="
export TEXTUP_BACKEND_URL_SETUP_ACCOUNT="https://app.textup.org/#/setup"
export TEXTUP_BACKEND_URL_SUPER_DASHBOARD="https://v2.textup.org/super"

# appended later on
# TEXTUP_BACKEND_AWS_ACCESS_KEY
# TEXTUP_BACKEND_AWS_SECRET_KEY
# TEXTUP_BACKEND_CDN_KEY_ID
# TEXTUP_BACKEND_DB_PASSWORD
# TEXTUP_BACKEND_DB_USERNAME
# TEXTUP_BACKEND_FFMPEG_COMMAND
# TEXTUP_BACKEND_FFMPEG_DIRECTORY
# TEXTUP_BACKEND_PUSHER_API_KEY
# TEXTUP_BACKEND_PUSHER_API_SECRET
# TEXTUP_BACKEND_SENDGRID_API_KEY
# TEXTUP_BACKEND_TEMP_DIRECTORY
# TEXTUP_BACKEND_TWILIO_AUTH
# TEXTUP_BACKEND_TWILIO_NUMBER_APP_ID
# TEXTUP_BACKEND_TWILIO_SID
