package org.textup

enum CallResponse {
	SELF_GREETING,
    SELF_ERROR,
    SELF_CONNECTING,
    BRIDGE_CONFIRM_CONNECT,
    BRIDGE_CONNECT,
    VOICEMAIL,
    CONNECTING,
    DEST_NOT_FOUND,
    TEAM_GREETING,
    TEAM_ERROR,
    TEAM_ANNOUNCEMENTS,
    TEAM_NO_ANNOUNCEMENTS,
    TEAM_SUBSCRIBE_ALL,
    TEAM_UNSUBSCRIBE_ALL,
    ANNOUNCEMENT,
    ANNOUNCEMENT_UNSUBSCRIBE_ONE,
    ANNOUNCEMENT_UNSUBSCRIBE_ALL,
    SERVER_ERROR
}
