package org.textup

enum TextResponse {
	STAFF_AWAY,
	STAFF_SELF_GREETING,
	TEAM_INSTRUCTIONS,
	TEAM_INSTRUCTIONS_SUBSCRIBED,
	TEAM_ANNOUNCEMENTS,
	TEAM_NO_ANNOUNCEMENTS,
	TEAM_SUBSCRIBE_ALL,
	TEAM_UNSUBSCRIBE_ALL,
	TEAM_UNSUBSCRIBE_ONE,
	NOT_FOUND,
	SERVER_ERROR
}
