package org.textup

enum TextResponse {
	STAFF_AWAY,
	TEAM_INSTRUCTIONS,
	TEAM_INSTRUCTIONS_SUBSCRIBED,
	TEAM_ANNOUNCEMENTS,
	TEAM_NO_ANNOUNCEMENTS,
	TEAM_SUBSCRIBE_ALL,
	TEAM_UNSUBSCRIBE_ALL,
	TEAM_UNSUBSCRIBE_ONE,
	NOT_FOUND,
	SERVER_ERROR
}